// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type GameLog struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	GameID    int32
	UserID    uuid.UUID
	Shelf     string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
}
