// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Genres      []string
	Image       string
	ReleaseDate time.Time
}

type GameLog struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	GameID    int32
	UserID    uuid.UUID
	Shelf     string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
}
