// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Genres      []string
	Image       string
	ReleaseDate time.Time
}

type GameLog struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	GameID    int32
	UserID    string
	Shelf     string
	Rating    int32
}

type User struct {
	ID                string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Name              string
	Email             string
	Avatarurl         string
	Provider          string
	Nickname          string
	AccessToken       string
	AccessTokenSecret string
	RefreshToken      string
	ExpiresAt         time.Time
	IDToken           string
	Username          string
}
