// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id,created_at,updated_at,name,email,avatarURL,provider,nickname,access_token,access_token_secret,refresh_token,expires_at,id_token,username)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
ON CONFLICT(id)
DO UPDATE SET updated_at=CURRENT_TIMESTAMP, username=$14
RETURNING id, created_at, updated_at, name, email, avatarurl, provider, nickname, access_token, access_token_secret, refresh_token, expires_at, id_token, username
`

type CreateUserParams struct {
	ID                string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Name              string
	Email             string
	Avatarurl         string
	Provider          string
	Nickname          string
	AccessToken       string
	AccessTokenSecret string
	RefreshToken      string
	ExpiresAt         time.Time
	IDToken           string
	Username          string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Email,
		arg.Avatarurl,
		arg.Provider,
		arg.Nickname,
		arg.AccessToken,
		arg.AccessTokenSecret,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.IDToken,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Avatarurl,
		&i.Provider,
		&i.Nickname,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.IDToken,
		&i.Username,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, created_at, updated_at, name, email, avatarurl, provider, nickname, access_token, access_token_secret, refresh_token, expires_at, id_token, username FROM users WHERE access_token=$1
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, accessToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKey, accessToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Avatarurl,
		&i.Provider,
		&i.Nickname,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.IDToken,
		&i.Username,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, name, email, avatarurl, provider, nickname, access_token, access_token_secret, refresh_token, expires_at, id_token, username FROM users WHERE id=$1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Avatarurl,
		&i.Provider,
		&i.Nickname,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.IDToken,
		&i.Username,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, email, avatarurl, username FROM users WHERE username=$1
`

type GetUserByUsernameRow struct {
	ID        string
	Name      string
	Email     string
	Avatarurl string
	Username  string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Avatarurl,
		&i.Username,
	)
	return i, err
}
